
const generateBtn = document.getElementById("generateBtn");
const memoBox = document.getElementById("memoBox");

generateBtn.onclick = () => {

const recipient = document.getElementById("recipient").value.trim();
const amount = document.getElementById("amount").value.trim();
const purpose = document.getElementById("purpose").value.trim();

if(recipient === "" || amount === "" || purpose === ""){
alert("Please fill all fields.");
return;
}

const reference = "ARC-" + Date.now();

const memo =
`Reference: ${reference}

Recipient: ${recipient}

Amount: ${amount} USDC

Purpose:
${purpose}

Generated by ArcMemoAI`;

memoBox.textContent = memo;

};
const connectBtn = document.getElementById("connectBtn");
const walletBox = document.getElementById("wallet");

let provider;
let signer;

connectBtn.onclick = async () => {

    if (!window.ethereum) {
        alert("Please install MetaMask.");
        return;
    }

    try {

        await window.ethereum.request({
            method: "eth_requestAccounts"
        });

        provider = new ethers.BrowserProvider(window.ethereum);

        signer = await provider.getSigner();

        const address = await signer.getAddress();

        walletBox.textContent =
            "Connected: " +
            address.slice(0, 6) +
            "..." +
            address.slice(-4);

    } catch (err) {

        console.log(err);

    }

};
