// ==
// ArcMemoAI
// ==

// Arc Testnet
const ARC_CHAIN_ID = "0x4cef52";
const ARC_RPC = "https://rpc.testnet.arc.network";
const ARC_NAME = "Arc Testnet";

// Elements
const connectBtn = document.getElementById("connectBtn");
const walletBox = document.getElementById("walletBox");
const generateBtn = document.getElementById("generateBtn");
const memoBox = document.getElementById("memoBox");
const statusBox = document.getElementById("status");

// Wallet
let provider;
let signer;

// --
// Status Message
// --
function showStatus(message, type = "info") {
    statusBox.className = type;
    statusBox.style.display = "block";
    statusBox.textContent = message;
}

// --
// Switch Network
// --
async function switchToArc() {

    try {

        await window.ethereum.request({
            method: "wallet_switchEthereumChain",
            params: [{ chainId: ARC_CHAIN_ID }]
        });

    } catch (err) {

        if (err.code === 4902) {

            await window.ethereum.request({

                method: "wallet_addEthereumChain",

                params: [{

                    chainId: ARC_CHAIN_ID,

                    chainName: ARC_NAME,

                    rpcUrls: [ARC_RPC],

                    nativeCurrency: {

                        name: "USDC",

                        symbol: "USDC",

                        decimals: 6

                    }

                }]

            });

        } else {

            throw err;

        }

    }

}

// --
// Connect Wallet
// --
connectBtn.onclick = async () => {

    if (!window.ethereum) {

        alert("Please install MetaMask.");

        return;

    }

    try {

        await window.ethereum.request({
            method: "eth_requestAccounts"
        });

        await switchToArc();

        provider = new ethers.BrowserProvider(window.ethereum);

        signer = await provider.getSigner();

        const address = await signer.getAddress();

        walletBox.textContent =
            "Connected: " +
            address.slice(0, 6) +
            "..." +
            address.slice(-4);

        showStatus("Wallet Connected", "success");

    } catch (err) {

        console.log(err);

        showStatus("Connection Failed", "error");

    }

};

// --
// Generate Memo
// --
generateBtn.onclick = () => {

    const recipient =
        document.getElementById("recipient").value.trim();

    const amount =
        document.getElementById("amount").value.trim();

    const purpose =
        document.getElementById("purpose").value.trim();

    if (!recipient || !amount || !purpose) {

        alert("Please fill all fields.");

        return;

    }

    const reference =

        "ARC-" +

        Math.floor(Date.now() / 1000);

    const memo =

`Reference: ${reference}

Recipient: ${recipient}

Amount: ${amount} USDC

Purpose:
${purpose}

Generated by ArcMemoAI`;

    memoBox.textContent = memo;

    showStatus("Memo Generated Successfully", "success");

};
