
const generateBtn = document.getElementById("generateBtn");
const memoBox = document.getElementById("memoBox");

generateBtn.onclick = () => {

const recipient = document.getElementById("recipient").value.trim();
const amount = document.getElementById("amount").value.trim();
const purpose = document.getElementById("purpose").value.trim();

if(recipient === "" || amount === "" || purpose === ""){
alert("Please fill all fields.");
return;
}

const reference = "ARC-" + Date.now();

const memo =
`Reference: ${reference}

Recipient: ${recipient}

Amount: ${amount} USDC

Purpose:
${purpose}

Generated by ArcMemoAI`;

memoBox.textContent = memo;

};
